/*
 * generated by Xtext 2.10.0
 */
package com.regnosys.rosetta.formatting2;

import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.FormatterRequest;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatting;
import org.eclipse.xtext.formatting2.ITextReplacer;
import org.eclipse.xtext.formatting2.regionaccess.IHiddenRegion;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegionsFinder;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

import com.regnosys.rosetta.rosetta.ExternalAnnotationSource;
import com.regnosys.rosetta.rosetta.Import;
import com.regnosys.rosetta.rosetta.ParametrizedRosettaType;
import com.regnosys.rosetta.rosetta.RosettaBasicType;
import com.regnosys.rosetta.rosetta.RosettaBody;
import com.regnosys.rosetta.rosetta.RosettaCardinality;
import com.regnosys.rosetta.rosetta.RosettaClassSynonym;
import com.regnosys.rosetta.rosetta.RosettaCorpus;
import com.regnosys.rosetta.rosetta.RosettaDefinable;
import com.regnosys.rosetta.rosetta.RosettaDocReference;
import com.regnosys.rosetta.rosetta.RosettaEnumSynonym;
import com.regnosys.rosetta.rosetta.RosettaEnumValue;
import com.regnosys.rosetta.rosetta.RosettaEnumValueReference;
import com.regnosys.rosetta.rosetta.RosettaEnumeration;
import com.regnosys.rosetta.rosetta.RosettaExternalClass;
import com.regnosys.rosetta.rosetta.RosettaExternalEnum;
import com.regnosys.rosetta.rosetta.RosettaExternalEnumValue;
import com.regnosys.rosetta.rosetta.RosettaExternalFunction;
import com.regnosys.rosetta.rosetta.RosettaExternalRegularAttribute;
import com.regnosys.rosetta.rosetta.RosettaExternalSynonym;
import com.regnosys.rosetta.rosetta.RosettaModel;
import com.regnosys.rosetta.rosetta.RosettaPackage;
import com.regnosys.rosetta.rosetta.RosettaParameter;
import com.regnosys.rosetta.rosetta.RosettaRootElement;
import com.regnosys.rosetta.rosetta.RosettaRule;
import com.regnosys.rosetta.rosetta.RosettaScope;
import com.regnosys.rosetta.rosetta.RosettaSegment;
import com.regnosys.rosetta.rosetta.RosettaSynonym;
import com.regnosys.rosetta.rosetta.RosettaSynonymSource;
import com.regnosys.rosetta.rosetta.RosettaTypeAlias;
import com.regnosys.rosetta.rosetta.TypeCall;
import com.regnosys.rosetta.rosetta.TypeCallArgument;
import com.regnosys.rosetta.rosetta.TypeParameter;
import com.regnosys.rosetta.rosetta.expression.RosettaExpression;
import com.regnosys.rosetta.rosetta.simple.Annotation;
import com.regnosys.rosetta.rosetta.simple.AnnotationRef;
import com.regnosys.rosetta.rosetta.simple.Attribute;
import com.regnosys.rosetta.rosetta.simple.Choice;
import com.regnosys.rosetta.rosetta.simple.Condition;
import com.regnosys.rosetta.rosetta.simple.Data;
import com.regnosys.rosetta.rosetta.simple.Function;
import com.regnosys.rosetta.rosetta.simple.FunctionDispatch;
import com.regnosys.rosetta.rosetta.simple.Operation;
import com.regnosys.rosetta.rosetta.simple.Segment;
import com.regnosys.rosetta.rosetta.simple.ShortcutDeclaration;
import com.regnosys.rosetta.services.RosettaGrammarAccess;

import jakarta.inject.Inject;

public class RosettaFormatter extends AbstractRosettaFormatter2 {

	private static final Procedure1<? super IHiddenRegionFormatter> NO_SPACE = IHiddenRegionFormatter::noSpace;
	private static final Procedure1<? super IHiddenRegionFormatter> ONE_SPACE = IHiddenRegionFormatter::oneSpace;

	@Inject
	private RosettaGrammarAccess grammarAccess;
	@Inject
	private RosettaExpressionFormatter expressionFormatter;
	@Inject
	private FormattingUtil formattingUtil;

	@Override
	protected void initialize(FormatterRequest request) {
		super.initialize(request);
		expressionFormatter.initialize(request);
	}

	@Override
	public void format(Object obj, IFormattableDocument document) {
		if (obj instanceof XtextResource) {
			_format((XtextResource) obj, document);
		} else if (obj instanceof RosettaModel) {
			format((RosettaModel) obj, document);
		} else if (obj instanceof Import) {
			format((Import) obj, document);
		} else if (obj instanceof RosettaScope) {
			format((RosettaScope) obj, document);
		} else if (obj instanceof RosettaBasicType) {
			format((RosettaBasicType) obj, document);
		} else if (obj instanceof RosettaTypeAlias) {
			format((RosettaTypeAlias) obj, document);
		} else if (obj instanceof TypeParameter) {
			format((TypeParameter) obj, document);
		} else if (obj instanceof RosettaExternalFunction) {
			format((RosettaExternalFunction) obj, document);
		} else if (obj instanceof RosettaParameter) {
			format((RosettaParameter) obj, document);
		} else if (obj instanceof RosettaBody) {
			format((RosettaBody) obj, document);
		} else if (obj instanceof RosettaCorpus) {
			format((RosettaCorpus) obj, document);
		} else if (obj instanceof RosettaSegment) {
			format((RosettaSegment) obj, document);
		} else if (obj instanceof Choice) {
			format((Choice) obj, document);
		} else if (obj instanceof Data) {
			// Choice already handled above
			format((Data) obj, document);
		} else if (obj instanceof Annotation) {
			format((Annotation) obj, document);
		} else if (obj instanceof Attribute) {
			format((Attribute) obj, document);
		} else if (obj instanceof TypeCall) {
			format((TypeCall) obj, document);
		} else if (obj instanceof TypeCallArgument) {
			format((TypeCallArgument) obj, document);
		} else if (obj instanceof Condition) {
			format((Condition) obj, document);
		} else if (obj instanceof AnnotationRef) {
			format((AnnotationRef) obj, document);
		} else if (obj instanceof Function) {
			// FunctionDispatch is a subtype of Function and is handled within format(Function, ...)
			format((Function) obj, document);
		} else if (obj instanceof RosettaEnumValueReference) {
			format((RosettaEnumValueReference) obj, document);
		} else if (obj instanceof ShortcutDeclaration) {
			format((ShortcutDeclaration) obj, document);
		} else if (obj instanceof Operation) {
			format((Operation) obj, document);
		} else if (obj instanceof Segment) {
			format((Segment) obj, document);
		} else if (obj instanceof RosettaDocReference) {
			format((RosettaDocReference) obj, document);
		} else if (obj instanceof RosettaClassSynonym) {
			format((RosettaClassSynonym) obj, document);
		} else if (obj instanceof RosettaSynonym) {
			format((RosettaSynonym) obj, document);
		} else if (obj instanceof RosettaEnumeration) {
			format((RosettaEnumeration) obj, document);
		} else if (obj instanceof RosettaEnumValue) {
			format((RosettaEnumValue) obj, document);
		} else if (obj instanceof RosettaEnumSynonym) {
			format((RosettaEnumSynonym) obj, document);
		} else if (obj instanceof RosettaExternalSynonym) {
			format((RosettaExternalSynonym) obj, document);
		} else if (obj instanceof RosettaExpression) {
			format((RosettaExpression) obj, document);
		} else if (obj instanceof RosettaRule) {
			format((RosettaRule) obj, document);
		} else if (obj instanceof ExternalAnnotationSource) {
			// RosettaExternalRuleSource and RosettaExternalSynonymSource both implement
			// ExternalAnnotationSource; the single dispatch case handles them all.
			// RosettaExternalSynonymSource also extends RosettaSynonymSource, so this
			// more specific case must be checked before the RosettaSynonymSource one below.
			format((ExternalAnnotationSource) obj, document);
		} else if (obj instanceof RosettaSynonymSource) {
			format((RosettaSynonymSource) obj, document);
		} else if (obj instanceof RosettaExternalClass) {
			format((RosettaExternalClass) obj, document);
		} else if (obj instanceof RosettaExternalEnum) {
			format((RosettaExternalEnum) obj, document);
		} else if (obj instanceof RosettaExternalRegularAttribute) {
			format((RosettaExternalRegularAttribute) obj, document);
		} else if (obj instanceof RosettaExternalEnumValue) {
			format((RosettaExternalEnumValue) obj, document);
		} else if (obj instanceof EObject) {
			// Any other EObject: recurse into its children, mirroring the inherited
			// AbstractFormatter2._format(EObject, IFormattableDocument) dispatch case.
			_format((EObject) obj, document);
		}
		// Any other (non-EObject) object: no-op (mirrors the inherited
		// AbstractFormatter2._format(Object, IFormattableDocument) / _format(Void, ...) cases).
	}

	private void format(RosettaModel rosettaModel, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaModelElements modelGrammarAccess = grammarAccess.getRosettaModelAccess();
		if (regionFor(rosettaModel).keyword(modelGrammarAccess.getOverriddenOverrideKeyword_0_0()) != null) {
			document.append(
					document.prepend(
							regionFor(rosettaModel).keyword(modelGrammarAccess.getOverriddenOverrideKeyword_0_0()),
							IHiddenRegionFormatter::noSpace),
					IHiddenRegionFormatter::oneSpace);
		} else {
			document.prepend(regionFor(rosettaModel).keyword(modelGrammarAccess.getNamespaceKeyword_1()),
					IHiddenRegionFormatter::noSpace);
		}
		document.append(regionFor(rosettaModel).keyword(modelGrammarAccess.getNamespaceKeyword_1()),
				IHiddenRegionFormatter::oneSpace);

		RosettaScope scope = rosettaModel.getScope();
		if (scope != null) {
			document.format(document.prepend(scope, IHiddenRegionFormatter::newLine));
		}

		document.append(
				document.prepend(regionFor(rosettaModel).keyword(modelGrammarAccess.getVersionKeyword_5_0()),
						IHiddenRegionFormatter::newLine),
				IHiddenRegionFormatter::oneSpace);

		Import firstImport = headOrNull(rosettaModel.getImports());
		if (firstImport != null) {
			document.format(document.prepend(firstImport, f -> f.setNewLines(2)));
		}
		tail(rosettaModel.getImports()).forEach(imp -> {
			document.prepend(imp, IHiddenRegionFormatter::newLine);
			document.format(imp);
		});

		List<Class<? extends RosettaRootElement>> groupedElementTypes = List.of(
				com.regnosys.rosetta.rosetta.RosettaBody.class,
				com.regnosys.rosetta.rosetta.RosettaCorpus.class,
				com.regnosys.rosetta.rosetta.RosettaSegment.class,
				com.regnosys.rosetta.rosetta.RosettaBasicType.class,
				com.regnosys.rosetta.rosetta.RosettaRecordType.class,
				com.regnosys.rosetta.rosetta.RosettaExternalFunction.class,
				com.regnosys.rosetta.rosetta.RosettaMetaType.class);
		Class<? extends RosettaRootElement> lastType = null;
		for (RosettaRootElement elem : rosettaModel.getElements()) {
			// Root elements are separated by an empty lines, except
			// for elements such as `metaType`s, `basicType`s, etc.
			// They are grouped together.
			if (groupedElementTypes.stream().anyMatch(type -> type.isInstance(elem))) {
				if (elem.getClass().equals(lastType)) {
					document.prepend(elem, f -> f.setNewLines(1, 1, 2));
				} else {
					document.prepend(elem, f -> f.setNewLines(2));
				}
			} else {
				document.prepend(elem, f -> f.setNewLines(2));
			}
			document.format(elem);
			lastType = elem.getClass();
		}

		// Always end with a single newline
		document.append(nextHiddenRegion(rosettaModel).getPreviousSemanticRegion(), IHiddenRegionFormatter::newLine);
	}

	private void format(Import ele, IFormattableDocument document) {
		RosettaGrammarAccess.ImportElements importGrammarAccess = grammarAccess.getImportAccess();
		document.append(regionFor(ele).keyword(importGrammarAccess.getImportKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.append(
				document.prepend(regionFor(ele).keyword(importGrammarAccess.getAsKeyword_2_0()),
						IHiddenRegionFormatter::oneSpace),
				IHiddenRegionFormatter::oneSpace);
	}

	private void format(RosettaScope ele, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaScopeElements scopeGrammarAccess = grammarAccess.getRosettaScopeAccess();
		document.append(regionFor(ele).keyword(scopeGrammarAccess.getScopeKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
	}

	private void format(RosettaBasicType ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getRosettaBasicTypeAccess().getBasicTypeKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		formatTypeParameters(ele, document);
	}

	private void format(RosettaTypeAlias ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getRosettaTypeAliasAccess().getTypeAliasKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		formatTypeParameters(ele, document);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);

		formattingUtil.indentInner(ele, regionFor(ele).keyword(":").getNextHiddenRegion(), document);
		formattingUtil.formatInlineOrMultiline(document, ele,
				doc -> {
					doc.format(doc.prepend(ele.getTypeCall(), IHiddenRegionFormatter::oneSpace));
					ele.getConditions().forEach(cond -> {
						doc.prepend(cond, f -> f.setNewLines(2));
						doc.format(cond);
					});
				},
				doc -> {
					doc.format(doc.prepend(ele.getTypeCall(), IHiddenRegionFormatter::newLine));
					ele.getConditions().forEach(cond -> {
						doc.prepend(cond, f -> f.setNewLines(2));
						doc.format(cond);
					});
				});
	}

	private void formatTypeParameters(ParametrizedRosettaType ele, IFormattableDocument document) {
		document.prepend(regionFor(ele).keyword("("), IHiddenRegionFormatter::noSpace);
		ele.getParameters().forEach(document::format);

		if (ele.getParameters().stream().anyMatch(p -> p.getDefinition() != null)) {
			// Format multiline
			document.interior(
					document.append(regionFor(ele).keyword("("), IHiddenRegionFormatter::newLine),
					document.prepend(regionFor(ele).keyword(")"), IHiddenRegionFormatter::newLine),
					IHiddenRegionFormatter::indent);
			ele.getParameters().forEach(p -> document.append(p, IHiddenRegionFormatter::newLine));
			regionFor(ele).keywords(",").forEach(comma -> document.append(comma, IHiddenRegionFormatter::oneSpace));
		} else {
			// Format single line
			document.append(regionFor(ele).keyword("("), IHiddenRegionFormatter::noSpace);
			document.prepend(regionFor(ele).keyword(")"), IHiddenRegionFormatter::noSpace);
			regionFor(ele).keywords(",").forEach(comma -> {
				document.prepend(comma, IHiddenRegionFormatter::noSpace);
				document.append(comma, IHiddenRegionFormatter::oneSpace);
			});
		}
	}

	private void format(TypeParameter ele, IFormattableDocument document) {
		document.format(document.prepend(ele.getTypeCall(), IHiddenRegionFormatter::oneSpace));
		formatDefinition(ele, document);
	}

	private void format(RosettaExternalFunction ele, IFormattableDocument document) {
		document.surround(regionFor(ele).keyword(grammarAccess.getRosettaLibraryFunctionAccess().getFunctionKeyword_1()),
				IHiddenRegionFormatter::oneSpace);
		document.surround(regionFor(ele).keyword("("), IHiddenRegionFormatter::noSpace);
		document.append(
				document.prepend(regionFor(ele).keyword(")"), IHiddenRegionFormatter::noSpace),
				IHiddenRegionFormatter::oneSpace);
		regionFor(ele).keywords(",").forEach(comma -> {
			document.prepend(comma, IHiddenRegionFormatter::noSpace);
			document.append(comma, IHiddenRegionFormatter::oneSpace);
		});
		ele.getParameters().forEach(document::format);
		formatDefinition(ele, document);
	}

	private void format(RosettaParameter ele, IFormattableDocument document) {
		document.format(document.prepend(ele.getTypeCall(), IHiddenRegionFormatter::oneSpace));
	}

	private void format(RosettaBody ele, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaBodyElements bodyGrammarAccess = grammarAccess.getRosettaBodyAccess();
		document.surround(regionFor(ele).assignment(bodyGrammarAccess.getBodyTypeAssignment_1()),
				IHiddenRegionFormatter::oneSpace);
		formatDefinition(ele, document);
	}

	private void format(RosettaCorpus ele, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaCorpusElements corpusGrammarAccess = grammarAccess.getRosettaCorpusAccess();
		document.prepend(regionFor(ele).assignment(corpusGrammarAccess.getCorpusTypeAssignment_1()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).assignment(corpusGrammarAccess.getBodyAssignment_2()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).assignment(corpusGrammarAccess.getDisplayNameAssignment_3()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).assignment(grammarAccess.getRosettaNamedAccess().getNameAssignment()),
				IHiddenRegionFormatter::oneSpace);
		formatDefinition(ele, document);
	}

	private void format(RosettaSegment ele, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaSegmentElements segmentGrammarAccess = grammarAccess.getRosettaSegmentAccess();
		document.prepend(regionFor(ele).assignment(segmentGrammarAccess.getNameAssignment_1()),
				IHiddenRegionFormatter::oneSpace);
	}

	private void format(Choice ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getChoiceAccess().getChoiceKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formattingUtil.indentInner(ele, document);
		formatDefinition(ele, document);
		Attribute firstAttribute = headOrNull(ele.getAttributes());
		if (firstAttribute != null) {
			document.format(document.prepend(firstAttribute, f -> f.setNewLines(1, 2, 2)));
		}
		tail(ele.getAttributes()).forEach(attr -> {
			document.prepend(attr, IHiddenRegionFormatter::newLine);
			document.format(attr);
		});
	}

	private void format(Data ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getDataAccess().getTypeKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.append(regionFor(ele).keyword(grammarAccess.getDataAccess().getExtendsKeyword_2_0()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);
		formattingUtil.indentInner(ele, document);
		ele.getSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
		ele.getAnnotations().forEach(ann -> {
			document.prepend(ann, IHiddenRegionFormatter::newLine);
			document.format(ann);
		});
		ele.getReferences().forEach(ref -> {
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});
		Attribute firstAttribute = headOrNull(ele.getAttributes());
		if (firstAttribute != null) {
			document.format(document.prepend(firstAttribute, f -> f.setNewLines(1, 2, 2)));
		}
		tail(ele.getAttributes()).forEach(attr -> {
			document.prepend(attr, IHiddenRegionFormatter::newLine);
			document.format(attr);
		});
		ele.getConditions().forEach(cond -> {
			document.prepend(cond, f -> f.setNewLines(2));
			document.format(cond);
		});
	}

	private void format(Annotation ele, IFormattableDocument document) {
		RosettaGrammarAccess.AnnotationElements annotationGrammarAccess = grammarAccess.getAnnotationAccess();
		document.append(regionFor(ele).keyword(annotationGrammarAccess.getAnnotationKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);
		formattingUtil.indentInner(ele, document);

		ISemanticRegion left = regionFor(ele).keyword("[");
		if (left != null) {
			ISemanticRegion right = regionFor(ele).keyword("]");
			document.append(left, IHiddenRegionFormatter::noSpace);
			document.prepend(right, IHiddenRegionFormatter::noSpace);
			formattingUtil.singleSpacesUntil(document, left.getNextHiddenRegion().getNextHiddenRegion(),
					right.getPreviousHiddenRegion());
		}

		Attribute firstAttribute = headOrNull(ele.getAttributes());
		if (firstAttribute != null) {
			document.format(document.prepend(firstAttribute, f -> f.setNewLines(1, 2, 2)));
		}
		tail(ele.getAttributes()).forEach(attr -> {
			document.prepend(attr, IHiddenRegionFormatter::newLine);
			document.format(attr);
		});
	}

	private void format(Attribute ele, IFormattableDocument document) {
		formatCardinality(ele.getCard(), document);
		formattingUtil.indentInner(ele, document);
		document.format(document.surround(ele.getTypeCall(), IHiddenRegionFormatter::oneSpace));
		formatDefinition(ele, document);
		ele.getReferences().forEach(ref -> {
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});
		ele.getAnnotations().forEach(ann -> {
			document.prepend(ann, IHiddenRegionFormatter::newLine);
			document.format(ann);
		});
		ele.getSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
	}

	private void format(TypeCall ele, IFormattableDocument document) {
		document.surround(regionFor(ele).keyword("("), IHiddenRegionFormatter::noSpace);
		document.prepend(regionFor(ele).keyword(")"), IHiddenRegionFormatter::noSpace);
		regionFor(ele).keywords(",").forEach(comma -> {
			document.prepend(comma, IHiddenRegionFormatter::noSpace);
			document.append(comma, IHiddenRegionFormatter::oneSpace);
		});
		ele.getArguments().forEach(document::format);
	}

	private void format(TypeCallArgument ele, IFormattableDocument document) {
		document.append(
				document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace),
				IHiddenRegionFormatter::oneSpace);
		expressionFormatter.formatExpression(ele.getValue(), document, FormattingMode.SINGLE_LINE);
	}

	private void formatCardinality(RosettaCardinality card, IFormattableDocument document) {
		document.append(regionFor(card).keyword("("), IHiddenRegionFormatter::noSpace);
		document.surround(regionFor(card).keyword(".."), IHiddenRegionFormatter::noSpace);
		document.prepend(regionFor(card).keyword(")"), IHiddenRegionFormatter::noSpace);
	}

	private EObject formatSingleLineAnnotation(EObject annotation, IFormattableDocument document) {
		ISemanticRegion left = regionFor(annotation).keyword("[");
		ISemanticRegion right = regionFor(annotation).keyword("]");

		document.append(left, IHiddenRegionFormatter::noSpace);
		document.prepend(right, IHiddenRegionFormatter::noSpace);
		formattingUtil.singleSpacesUntil(document, left.getNextHiddenRegion().getNextHiddenRegion(),
				right.getPreviousHiddenRegion());
		return annotation;
	}

	private void format(Condition ele, IFormattableDocument document) {
		document.prepend(regionFor(ele).assignment(grammarAccess.getRosettaNamedAccess().getNameAssignment()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);
		formattingUtil.indentInner(ele, document);
		ele.getAnnotations().forEach(ann -> {
			document.prepend(ann, IHiddenRegionFormatter::newLine);
			document.format(ann);
		});
		document.format(document.prepend(ele.getExpression(), IHiddenRegionFormatter::newLine));
	}

	private RosettaDefinable formatDefinition(RosettaDefinable ele, IFormattableDocument document) {
		if (ele.getDefinition() != null) {
			document.append(
					document.prepend(regionFor(ele).keyword("<"), IHiddenRegionFormatter::oneSpace),
					IHiddenRegionFormatter::noSpace);
			document.prepend(regionFor(ele).keyword(">"), IHiddenRegionFormatter::noSpace);

			// Force a new line after documentation
			IHiddenRegionFormatting formatting = createHiddenRegionFormatting();
			formatting.setPriority(IHiddenRegionFormatter.HIGH_PRIORITY);
			formatting.setNewLinesMin(1);
			ITextReplacer replacer = createHiddenRegionReplacer(
					regionFor(ele).keyword(">").getNextHiddenRegion(), formatting);
			document.addReplacer(replacer);
		}
		return ele;
	}

	private void format(AnnotationRef ele, IFormattableDocument document) {
		RosettaGrammarAccess.AnnotationRefElements annotationRefGrammarAccess = grammarAccess.getAnnotationRefAccess();
		document.append(regionFor(ele).keyword(annotationRefGrammarAccess.getLeftSquareBracketKeyword_0()), NO_SPACE);
		document.prepend(regionFor(ele).keyword(annotationRefGrammarAccess.getRightSquareBracketKeyword_3()), NO_SPACE);
		document.prepend(regionFor(ele).assignment(annotationRefGrammarAccess.getAttributeAssignment_2_0()), ONE_SPACE);
	}

	private void format(Function ele, IFormattableDocument document) {
		RosettaGrammarAccess.FunctionElements functionGrammarAccess = grammarAccess.getFunctionAccess();

		document.append(regionFor(ele).keyword(functionGrammarAccess.getFuncKeyword_0()),
				IHiddenRegionFormatter::oneSpace);

		if (ele instanceof FunctionDispatch) {
			FunctionDispatch dispatch = (FunctionDispatch) ele;
			document.surround(regionFor(ele).keyword(functionGrammarAccess.getLeftParenthesisKeyword_1_1_2()),
					IHiddenRegionFormatter::noSpace);
			document.append(
					document.prepend(regionFor(ele).keyword(functionGrammarAccess.getColonKeyword_1_1_4()),
							IHiddenRegionFormatter::noSpace),
					IHiddenRegionFormatter::oneSpace);
			document.format(dispatch.getValue());
			document.surround(regionFor(ele).keyword(functionGrammarAccess.getRightParenthesisKeyword_1_1_6()),
					IHiddenRegionFormatter::noSpace);
		}

		if (ele.getSuperFunction() != null) {
			document.surround(regionFor(ele).keyword(functionGrammarAccess.getExtendsKeyword_2_0()),
					IHiddenRegionFormatter::oneSpace);
		}

		document.prepend(regionFor(ele).keyword(functionGrammarAccess.getColonKeyword_3()),
				IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);

		formattingUtil.indentInner(ele, document);

		ele.getReferences().forEach(ref -> {
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});
		ele.getAnnotations().forEach(ann -> {
			document.prepend(ann, IHiddenRegionFormatter::newLine);
			document.format(ann);
		});

		ISemanticRegion inputsKW = regionFor(ele).keyword(functionGrammarAccess.getInputsKeyword_6_0());
		if (inputsKW != null) {
			document.prepend(inputsKW, IHiddenRegionFormatter::newLine);
			ISemanticRegion inputsColon = document.prepend(
					regionFor(ele).keyword(functionGrammarAccess.getColonKeyword_6_1()),
					IHiddenRegionFormatter::noSpace);
			document.set(
					inputsColon.getNextHiddenRegion(),
					nextHiddenRegion(lastOrNull(ele.getInputs())),
					IHiddenRegionFormatter::indent);
			ele.getInputs().forEach(input -> {
				document.prepend(input, IHiddenRegionFormatter::newLine);
				document.format(input);
			});
		}

		if (ele.getOutput() != null) { // might be null for dispatch functions!
			document.prepend(regionFor(ele).keyword(functionGrammarAccess.getOutputKeyword_7_0()),
					IHiddenRegionFormatter::newLine);
			document.prepend(regionFor(ele).keyword(functionGrammarAccess.getColonKeyword_7_1()),
					IHiddenRegionFormatter::noSpace);
			document.set(
					regionFor(ele).keyword(functionGrammarAccess.getColonKeyword_7_1()).getNextHiddenRegion(),
					nextHiddenRegion(ele.getOutput()),
					IHiddenRegionFormatter::indent);
			document.format(document.prepend(ele.getOutput(), IHiddenRegionFormatter::newLine));
		}

		ele.getShortcuts().forEach(shortcut -> {
			document.prepend(shortcut, f -> f.setNewLines(1, 1, 2));
			document.format(shortcut);
		});
		ele.getConditions().forEach(cond -> {
			document.prepend(cond, f -> f.setNewLines(1, 1, 2));
			document.format(cond);
		});
		ele.getOperations().forEach(op -> {
			document.prepend(op, f -> f.setNewLines(1, 1, 2));
			document.format(op);
		});
		ele.getPostConditions().forEach(cond -> {
			document.prepend(cond, f -> f.setNewLines(1, 1, 2));
			document.format(cond);
		});
	}

	private void format(RosettaEnumValueReference ele, IFormattableDocument document) {
		document.surround(regionFor(ele).keyword("->"), IHiddenRegionFormatter::oneSpace);
	}

	private void format(ShortcutDeclaration ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getShortcutDeclarationAccess().getAliasKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(":"), IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);
		formattingUtil.formatInlineOrMultiline(document, ele,
				doc -> {
					doc.format(doc.prepend(ele.getExpression(), IHiddenRegionFormatter::oneSpace));
				},
				doc -> {
					formattingUtil.indentInner(ele, doc);
					doc.format(doc.prepend(ele.getExpression(), IHiddenRegionFormatter::newLine));
				});
	}

	private void format(Operation ele, IFormattableDocument document) {
		RosettaGrammarAccess.OperationElements operationGrammarAccess = grammarAccess.getOperationAccess();

		document.append(regionFor(ele).keyword(operationGrammarAccess.getSetKeyword_0_0()),
				IHiddenRegionFormatter::oneSpace);
		document.append(regionFor(ele).keyword(operationGrammarAccess.getAddAddKeyword_0_1_0()),
				IHiddenRegionFormatter::oneSpace);
		if (ele.getPath() != null) {
			document.format(ele.getPath());
		}
		formatDefinition(ele, document);

		document.prepend(regionFor(ele).keyword(operationGrammarAccess.getColonKeyword_3()),
				IHiddenRegionFormatter::noSpace);
		formattingUtil.formatInlineOrMultiline(document, ele,
				doc -> {
					doc.format(doc.prepend(ele.getExpression(), IHiddenRegionFormatter::oneSpace));
				},
				doc -> {
					formattingUtil.indentInner(ele, doc);
					doc.format(doc.prepend(ele.getExpression(), IHiddenRegionFormatter::newLine));
				});
	}

	private void format(Segment ele, IFormattableDocument document) {
		document.surround(regionFor(ele).keyword("->"), IHiddenRegionFormatter::oneSpace);
		if (ele.getNext() != null) {
			document.format(ele.getNext());
		}
	}

	private void format(RosettaDocReference rosettaRegulatoryReference, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaDocReferenceElements docReferenceGrammarAccess = grammarAccess
				.getRosettaDocReferenceAccess();
		RosettaGrammarAccess.DocumentRationaleElements documentRationaleAccess = grammarAccess
				.getDocumentRationaleAccess();

		ISemanticRegion left = regionFor(rosettaRegulatoryReference).keyword("[");
		ISemanticRegion right = regionFor(rosettaRegulatoryReference).keyword("]");

		document.append(left, IHiddenRegionFormatter::noSpace);
		document.prepend(right, IHiddenRegionFormatter::noSpace);
		document.interior(left, right, IHiddenRegionFormatter::indent);
		formattingUtil.singleSpacesUntil(
				document,
				left.getNextHiddenRegion().getNextHiddenRegion(),
				nextHiddenRegion(rosettaRegulatoryReference.getDocReference()));
		rosettaRegulatoryReference.getRationales().forEach(rationale -> {
			regionFor(rationale).keywords(
					documentRationaleAccess.getRationaleKeyword_0_0(),
					documentRationaleAccess.getRationale_authorKeyword_1_0(),
					documentRationaleAccess.getRationaleKeyword_1_2_0(),
					documentRationaleAccess.getRationale_authorKeyword_0_2_0()).forEach(kw -> {
						document.prepend(kw, IHiddenRegionFormatter::newLine);
						document.append(kw, IHiddenRegionFormatter::oneSpace);
					});
		});
		document.append(
				document.prepend(
						regionFor(rosettaRegulatoryReference)
								.keyword(docReferenceGrammarAccess.getStructured_provisionKeyword_5_0()),
						IHiddenRegionFormatter::newLine),
				IHiddenRegionFormatter::oneSpace);
		document.append(
				document.prepend(
						regionFor(rosettaRegulatoryReference)
								.keyword(docReferenceGrammarAccess.getProvisionKeyword_6_0()),
						IHiddenRegionFormatter::newLine),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(
				regionFor(rosettaRegulatoryReference)
						.keyword(docReferenceGrammarAccess.getReportedFieldReportedFieldKeyword_7_0()),
				IHiddenRegionFormatter::newLine);
	}

	private void format(RosettaClassSynonym ele, IFormattableDocument document) {
		formatSingleLineAnnotation(ele, document);
	}

	private void format(RosettaSynonym ele, IFormattableDocument document) {
		formatSingleLineAnnotation(ele, document);
	}

	private void format(RosettaEnumeration ele, IFormattableDocument document) {
		document.append(regionFor(ele).keyword(grammarAccess.getEnumerationAccess().getEnumKeyword_0()),
				IHiddenRegionFormatter::oneSpace);
		document.prepend(regionFor(ele).keyword(grammarAccess.getEnumerationAccess().getColonKeyword_3()),
				IHiddenRegionFormatter::noSpace);
		formatDefinition(ele, document);
		formattingUtil.indentInner(ele, document);

		ele.getReferences().forEach(ref -> {
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});
		ele.getSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
		RosettaEnumValue firstEnumValue = headOrNull(ele.getEnumValues());
		if (firstEnumValue != null) {
			document.format(document.prepend(firstEnumValue, f -> f.setNewLines(1, 2, 2)));
		}
		tail(ele.getEnumValues()).forEach(enumValue -> {
			document.prepend(enumValue, IHiddenRegionFormatter::newLine);
			document.format(enumValue);
		});
	}

	private void format(RosettaEnumValue rosettaEnumValue, IFormattableDocument document) {
		formattingUtil.indentInner(formatDefinition(rosettaEnumValue, document), document);
		rosettaEnumValue.getReferences().forEach(ref -> {
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});
		rosettaEnumValue.getEnumSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
	}

	private void format(RosettaEnumSynonym rosettaEnumSynonym, IFormattableDocument document) {
		formatSingleLineAnnotation(rosettaEnumSynonym, document);
	}

	private void format(RosettaExternalSynonym externalSynonym, IFormattableDocument document) {
		formatSingleLineAnnotation(externalSynonym, document);
	}

	private void format(RosettaExpression ele, IFormattableDocument document) {
		expressionFormatter.formatExpression(ele, document);
	}

	private void format(RosettaRule ele, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaRuleElements ruleGrammarAccess = grammarAccess.getRosettaRuleAccess();

		ISemanticRegion firstKeyword = regionFor(ele).keyword(ruleGrammarAccess.getReportingKeyword_0_0());
		if (firstKeyword == null) {
			firstKeyword = regionFor(ele).keyword(ruleGrammarAccess.getEligibilityEligibilityKeyword_0_1_0());
		}

		document.append(firstKeyword, IHiddenRegionFormatter::oneSpace);
		document.append(regionFor(ele).keyword(ruleGrammarAccess.getRuleKeyword_1()),
				IHiddenRegionFormatter::oneSpace);
		document.surround(regionFor(ele).keyword(ruleGrammarAccess.getFromKeyword_3_0()),
				IHiddenRegionFormatter::oneSpace);
		document.format(ele.getInput());
		document.append(
				document.prepend(regionFor(ele).keyword(ruleGrammarAccess.getColonKeyword_4()),
						IHiddenRegionFormatter::noSpace),
				IHiddenRegionFormatter::oneSpace);
		formatDefinition(ele, document);

		formattingUtil.indentInner(ele, document);

		ele.getReferences().forEach(ref -> { // TODO: format references
			document.prepend(ref, IHiddenRegionFormatter::newLine);
			document.format(ref);
		});

		document.format(document.prepend(ele.getExpression(), IHiddenRegionFormatter::newLine));
		if (ele.getIdentifier() != null) {
			document.set(
					document.append(
							document.prepend(
									regionFor(ele).keyword(ruleGrammarAccess.getAsKeyword_6_1_1_0_0()),
									IHiddenRegionFormatter::newLine),
							IHiddenRegionFormatter::oneSpace)
							.getPreviousHiddenRegion(),
					regionFor(ele).assignment(ruleGrammarAccess.getIdentifierAssignment_6_1_1_0_1())
							.getNextHiddenRegion(),
					IHiddenRegionFormatter::indent);
		}
	}

	private void format(RosettaSynonymSource synonymSource, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaSynonymSourceElements synonymSourceGrammarAccess = grammarAccess
				.getRosettaSynonymSourceAccess();

		document.surround(regionFor(synonymSource).keyword(synonymSourceGrammarAccess.getSourceKeyword_1()),
				IHiddenRegionFormatter::oneSpace);
	}

	private void format(ExternalAnnotationSource externalAnnotationSource, IFormattableDocument document) {
		RosettaGrammarAccess.RosettaExternalSynonymSourceElements externalSynonymSourceGrammarAccess = grammarAccess
				.getRosettaExternalSynonymSourceAccess();
		RosettaGrammarAccess.RosettaExternalRuleSourceElements externalRuleSourceGrammarAccess = grammarAccess
				.getRosettaExternalRuleSourceAccess();

		document.surround(
				regionFor(externalAnnotationSource).keyword(externalSynonymSourceGrammarAccess.getSourceKeyword_1()),
				IHiddenRegionFormatter::oneSpace);
		document.surround(
				regionFor(externalAnnotationSource).keyword(externalRuleSourceGrammarAccess.getSourceKeyword_1()),
				IHiddenRegionFormatter::oneSpace);
		document.surround(
				regionFor(externalAnnotationSource).keyword(externalSynonymSourceGrammarAccess.getExtendsKeyword_3_0()),
				IHiddenRegionFormatter::oneSpace);
		document.surround(
				regionFor(externalAnnotationSource).keyword(externalRuleSourceGrammarAccess.getExtendsKeyword_3_0()),
				IHiddenRegionFormatter::oneSpace);

		indentedBraces(externalAnnotationSource, document);
		RosettaExternalClass firstClass = headOrNull(externalAnnotationSource.getExternalClasses());
		if (firstClass != null) {
			document.prepend(firstClass, IHiddenRegionFormatter::newLine);
		}
		tail(externalAnnotationSource.getExternalClasses())
				.forEach(externalClass -> document.prepend(externalClass, f -> f.setNewLines(2)));
		externalAnnotationSource.getExternalClasses().forEach(document::format);

		ISemanticRegion enumsKeyword = regionFor(externalAnnotationSource)
				.keyword(grammarAccess.getExternalAnnotationSourceAccess().getEnumsKeyword_2_0());
		if (enumsKeyword != null) {
			if (externalAnnotationSource.getExternalClasses().isEmpty()) {
				document.prepend(enumsKeyword, IHiddenRegionFormatter::newLine);
			} else {
				document.prepend(enumsKeyword, f -> f.setNewLines(2));
			}
			externalAnnotationSource.getExternalEnums().forEach(externalEnum -> {
				document.prepend(externalEnum, f -> f.setNewLines(2));
				document.format(externalEnum);
			});
		}
	}

	private void format(RosettaExternalClass externalClass, IFormattableDocument document) {
		document.prepend(regionFor(externalClass).keyword(":"), IHiddenRegionFormatter::noSpace);
		formattingUtil.indentInner(externalClass, document);
		externalClass.getRegularAttributes().forEach(attr -> {
			document.prepend(attr, IHiddenRegionFormatter::newLine);
			document.format(attr);
		});
	}

	private void format(RosettaExternalEnum externalEnum, IFormattableDocument document) {
		document.prepend(regionFor(externalEnum).keyword(":"), IHiddenRegionFormatter::noSpace);
		formattingUtil.indentInner(externalEnum, document);
		externalEnum.getRegularValues().forEach(value -> {
			document.prepend(value, IHiddenRegionFormatter::newLine);
			document.format(value);
		});
	}

	private void format(RosettaExternalRegularAttribute externalRegularAttribute, IFormattableDocument document) {
		document.append(
				regionFor(externalRegularAttribute)
						.feature(RosettaPackage.Literals.ROSETTA_EXTERNAL_REGULAR_ATTRIBUTE__OPERATOR),
				IHiddenRegionFormatter::oneSpace);
		formattingUtil.indentInner(externalRegularAttribute, document);
		externalRegularAttribute.getExternalSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
	}

	private void format(RosettaExternalEnumValue externalEnumValue, IFormattableDocument document) {
		document.append(
				regionFor(externalEnumValue)
						.feature(RosettaPackage.Literals.ROSETTA_EXTERNAL_ENUM_VALUE__OPERATOR),
				IHiddenRegionFormatter::oneSpace);
		formattingUtil.indentInner(externalEnumValue, document);
		externalEnumValue.getExternalEnumSynonyms().forEach(syn -> {
			document.prepend(syn, IHiddenRegionFormatter::newLine);
			document.format(syn);
		});
	}

	private void indentedBraces(EObject eObject, IFormattableDocument document) {
		ISemanticRegion lcurly = document.prepend(regionFor(eObject).keyword("{"), IHiddenRegionFormatter::newLine);
		ISemanticRegion rcurly = document.prepend(regionFor(eObject).keyword("}"), IHiddenRegionFormatter::newLine);
		document.interior(lcurly, rcurly, IHiddenRegionFormatter::indent);
	}

	// --- region navigation helpers ---

	private ISemanticRegionsFinder regionFor(EObject obj) {
		return textRegionExtensions.regionFor(obj);
	}

	private IHiddenRegion nextHiddenRegion(EObject obj) {
		return textRegionExtensions.nextHiddenRegion(obj);
	}

	private static <T> T headOrNull(List<T> list) {
		return list.isEmpty() ? null : list.get(0);
	}

	private static <T> List<T> tail(List<T> list) {
		return list.isEmpty() ? List.of() : list.subList(1, list.size());
	}

	private static <T> T lastOrNull(List<T> list) {
		return list.isEmpty() ? null : list.get(list.size() - 1);
	}
}
