/*
 * Copyright (c) REGnosys 2018 (www.regnosys.com) 
 * generated by Xtext 2.27.0
 */
package com.regnosys.rosetta.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class RosettaOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
