/*
 * Copyright (c) REGnosys 2018 (www.regnosys.com) 
 * generated by Xtext 2.39.0
 */
package com.regnosys.rosetta.ide;

import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.generator.IContextualOutputConfigurationProvider;
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.editor.quickfix.IQuickFixProvider;
import org.eclipse.xtext.ide.server.ICapabilitiesContributor;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.contentassist.ContentAssistService;
import org.eclipse.xtext.ide.server.formatting.FormattingService;
import org.eclipse.xtext.ide.server.hover.IHoverService;
import org.eclipse.xtext.service.OperationCanceledManager;

import com.regnosys.rosetta.generator.RosettaOutputConfigurationProvider;
import com.regnosys.rosetta.ide.contentassist.RosettaContentProposalProvider;
import com.regnosys.rosetta.ide.contentassist.cancellable.CancellableContentAssistService;
import com.regnosys.rosetta.ide.contentassist.cancellable.CancellableRosettaParser;
import com.regnosys.rosetta.ide.contentassist.cancellable.ICancellableContentAssistParser;
import com.regnosys.rosetta.ide.contentassist.cancellable.RosettaOperationCanceledManager;
import com.regnosys.rosetta.ide.formatting.RosettaFormattingService;
import com.regnosys.rosetta.ide.hover.RosettaDocumentationProvider;
import com.regnosys.rosetta.ide.hover.RosettaHoverService;
import com.regnosys.rosetta.ide.inlayhints.IInlayHintsResolver;
import com.regnosys.rosetta.ide.inlayhints.IInlayHintsService;
import com.regnosys.rosetta.ide.inlayhints.RosettaInlayHintsService;
import com.regnosys.rosetta.ide.overrides.IParentsService;
import com.regnosys.rosetta.ide.overrides.RosettaParentsService;
import com.regnosys.rosetta.ide.quickfix.ICodeActionProvider;
import com.regnosys.rosetta.ide.quickfix.IResolveCodeActionService;
import com.regnosys.rosetta.ide.quickfix.RosettaCodeActionProvider;
import com.regnosys.rosetta.ide.quickfix.RosettaCodeActionService;
import com.regnosys.rosetta.ide.quickfix.RosettaQuickFixProvider;
import com.regnosys.rosetta.ide.quickfix.RosettaResolveCodeActionService;
import com.regnosys.rosetta.ide.semantictokens.ISemanticTokenModifiersProvider;
import com.regnosys.rosetta.ide.semantictokens.ISemanticTokenTypesProvider;
import com.regnosys.rosetta.ide.semantictokens.ISemanticTokensService;
import com.regnosys.rosetta.ide.semantictokens.RosettaSemanticTokenModifiersProvider;
import com.regnosys.rosetta.ide.semantictokens.RosettaSemanticTokenTypesProvider;
import com.regnosys.rosetta.ide.semantictokens.RosettaSemanticTokensService;
import com.regnosys.rosetta.ide.server.RosettaCapabilitiesContributor;
import com.regnosys.rosetta.ide.textmate.RosettaTextMateGrammarUtil;
import com.regnosys.rosetta.ide.util.RangeUtils;

/**
 * Use this class to register ide components.
 */
public class RosettaIdeModule extends AbstractRosettaIdeModule {
	public Class<? extends IContextualOutputConfigurationProvider> bindIContextualOutputConfigurationProvider() {
		return RosettaOutputConfigurationProvider.class;
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return RosettaDocumentationProvider.class;
	}
	
	public Class<? extends RangeUtils> bindRangeUtils() {
		return RangeUtils.class;
	}
	
	public Class<? extends IInlayHintsResolver> bindIInlayHintsResolver() {
		return RosettaInlayHintsService.class;
	}
	
	public Class<? extends IInlayHintsService> bindIInlayHintsService() {
		return RosettaInlayHintsService.class;
	}
	
	public Class<? extends ISemanticTokenTypesProvider> bindISemanticTokenTypesProvider() {
		return RosettaSemanticTokenTypesProvider.class;
	}
	
	public Class<? extends ISemanticTokenModifiersProvider> bindISemanticTokenModifiersProvider() {
		return RosettaSemanticTokenModifiersProvider.class;
	}
	
	public Class<? extends ISemanticTokensService> bindISemanticTokensService() {
		return RosettaSemanticTokensService.class;
	}
	
	public Class<? extends RosettaTextMateGrammarUtil> bindRosettaTextMateGrammarUtil() {
		return RosettaTextMateGrammarUtil.class;
	}

	public Class<? extends FormattingService> bindFormattingService() {
		return RosettaFormattingService.class;
	}
	
	public Class<? extends IQuickFixProvider> bindIQuickFixProvider() {
		return RosettaQuickFixProvider.class;
	}
	
	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return RosettaCodeActionService.class;
	}
	
	public Class<? extends IResolveCodeActionService> bindIResolveCodeActionService() {
		return RosettaResolveCodeActionService.class;
	}
	
	public Class<? extends ICodeActionProvider> bindICodeActionProvider() {
		return RosettaCodeActionProvider.class;
	}
	
	public Class<? extends ICancellableContentAssistParser> bindICancellableContentAssistParser() {
		return CancellableRosettaParser.class;
	}
	
	public Class<? extends ContentAssistService> bindContentAssistService() {
		return CancellableContentAssistService.class;
	}
	
	public Class<? extends OperationCanceledManager> bindOperationCanceledManager() {
		return RosettaOperationCanceledManager.class;
	}
	
	public Class<? extends IHoverService> bindIHoverService() {
		return RosettaHoverService.class;
	}
	
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return RosettaContentProposalProvider.class;
	}
	
	public Class<? extends ICapabilitiesContributor> bindICapabilitiesContributor() {
		return RosettaCapabilitiesContributor.class;
	}
	
	public Class<? extends IParentsService> bindIParentsService() {
		return RosettaParentsService.class;
	}
}
