/*
 * generated by Xtext 2.10.0
 */
package com.regnosys.rosetta.tests

import com.regnosys.rosetta.tests.util.ModelHelper
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import javax.inject.Inject

@ExtendWith(InjectionExtension)
@InjectWith(RosettaInjectorProvider)
class RosettaTranslateParsingTest {

	@Inject extension ModelHelper
	
	@Test
	def void testTranslate() {
	    '''
	    metaType location string
	    
	    type Foo:
	    	a string (1..1)
	    		[metadata location]
	    
	    type Bar:
	    	b string (1..1)
	    	c string (1..1)
	    
	    translate source FooBar1 {
	        translate Bar to Foo {
	        	a: b
	        }
	           		// [meta location from c]
	    }
	    
	    translate source FooBar2 extends FooBar1 {
	        translate bar Bar, param string to Foo {
	        	a: bar -> b + param
	        }
	    }
	    '''.parseRosettaWithNoIssues
	}
}
