name: Maven Build
description: Run a Maven Build

inputs:
  build-command:
    description: The Maven command to build the project. The default is `package`.
    required: false
    # type: string  - `type` field is not supported (yet). See comment below.
    default: package
  run-tests:
    description: Whether or not to run tests. The default is true.
    required: false
    # type: boolean  - This is not supported (yet). All inputs are of type `string`. See https://github.com/actions/runner/issues/2238.
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven
        server-id: ossrh
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Build with Maven
      shell: bash
      run: mvn -B clean ${{ inputs.build-command }}${{ inputs.run-tests == 'false' && ' -DskipTests' || '' }}
